### ISSUE TITLE
Not working with aliases in webpack

### ISSUE THREAD

**Issue by dirkjf** [loilo/node-sass-yaml-importer#29]
If you have for example a file `config/frontend/variables/colors.scss` you can shorten the import statements by creating an alias in webpack, for example: `'variables': path.resolve(__dirname, 'config/frontend/variables')`, you can then use it like so:

```
@use '~variables/colors.scss';
```

Doing this with a YAML file (`@use '~variables/colors.yaml';`) does not work unfortunately. It would be great if this could be supported.

**Comment by loilo** [comment]
I had this happen to me before, but it never occurred to me that this could actually be a problem with the plugin. I'll take a look, thank you for the gentle push.

**Comment by loilo** [comment]
There is now first-class support for `sass-loader` in v8 which supports resolving requests just as webpack/rspack does, see [the readme](README.md#sass-loader-for-webpackrspack).
